# Macro file for the initialization
# in interactive session
#
# Set some default verbose
#
/control/verbose 2
/control/saveHistory
/run/verbose 2
#
# Change the default number of threads (in multi-threaded mode)
#/run/numberOfThreads 4
#

# Define Geometry Parameters

/NCamera/Geometry/distance_plane 40. cm
/NCamera/Geometry/scin_distance 20. cm

# Initialize kernel
/run/initialize

#
# Visualization setting
/control/execute vis.mac

/run/beamOn 1
