# Macro

# Can be run in batch, without graphic
# or interactively: Idle> /control/execute run1.mac

# Change the default number of workers (in multi-threading mode)
#/run/numberOfThreads 4

# Define Geometry Parameters

/NCamera/Geometry/distance_plane 40. cm
/NCamera/Geometry/scin_distance 20. cm

#/gps/particle neutron

#/gps/pos/type Beam
#/gps/direction 0 1 0
#/gps/pos/centre  0 -300. -11. cm
#/gps/pos/shape Circle
#/gps/pos/radius 1. cm
#/gps/ene/type Mono
#/gps/ene/mono 1. MeV


# Initialize kernel
/run/initialize

/tracking/verbose 0
#/tracking/verbose 1

/run/beamOn 100000000
