# Macro file for the visualization setting for the initialization phase
# when running in interactive mode
#

# Use these open statements to open selected visualization
#
# Use this open statement to create an OpenGL view:
/vis/open OGL 600x600-0+0
#
# Use this open statement to create an OpenInventor view:
#/vis/open OIX
#
# Use this open statement to create a .prim file suitable for
# viewing in DAWN:
#/vis/open DAWNFILE
#
# Use this open statement to create a .heprep file suitable for
# viewing in HepRApp:
#/vis/open HepRepFile
#
# Use this open statement to create a .wrl file suitable for
# viewing in a VRML viewer:
#/vis/open VRML2FILE
#
# Disable auto refresh and quieten vis messages whilst scene and
# trajectories are established:
/vis/viewer/set/autoRefresh false
/vis/verbose errors
#
# Draw geometry:
/vis/drawVolume
#
# Specify view angle:
/vis/viewer/set/viewpointThetaPhi 90. 180.
#
# Specify zoom value:
#/vis/viewer/zoom 2.
#
# Specify style (surface, wireframe, auxiliary edges,...)
#/vis/viewer/set/style wireframe
#/vis/viewer/set/auxiliaryEdge true
#/vis/viewer/set/lineSegmentsPerCircle 100
#
# Draw coordinate axes:
#/vis/scene/add/axes 0 0 0 1 m
#
# Draw smooth trajectories at end of event, showing trajectory points
# as markers 2 pixels wide:
/vis/scene/add/trajectories smooth
/vis/modeling/trajectories/create/drawByCharge
/vis/modeling/trajectories/drawByCharge-0/default/setDrawStepPts true
/vis/modeling/trajectories/drawByCharge-0/default/setStepPtsSize 1
# (if too many tracks cause core dump => /tracking/storeTrajectory 0)
#
# Draw hits at end of event:
#/vis/scene/add/hits
#
# To draw only gammas:
#/vis/filtering/trajectories/create/particleFilter
#/vis/filtering/trajectories/particleFilter-0/add gamma
#
# To invert the above, drawing all particles except gammas,
# keep the above two lines but also add:
#/vis/filtering/trajectories/particleFilter-0/invert true
#
# Many other options are available with /vis/modeling and /vis/filtering.
# For example, to select colour by particle ID:
#/vis/modeling/trajectories/create/drawByParticleID
#/vis/modeling/trajectories/drawByParticleID-0/default/setDrawStepPts true
# To select or override default colours (note: e+ is blue by default):
#/vis/modeling/trajectories/list
#/vis/modeling/trajectories/drawByParticleID-0/set e+ yellow
#
# To superimpose all of the events from a given run:
/vis/scene/endOfEventAction accumulate
#
# Re-establish auto refreshing and verbosity:
/vis/viewer/set/autoRefresh true
/vis/verbose warnings
#
# For file-based drivers, use this to create an empty detector view:
#/vis/viewer/flush


# Decorations
# Name
/vis/set/textColour green
/vis/set/textLayout right
/vis/scene/add/text2D 0.9 -.9 24 ! ! exampleED
# or, if your system does not support right-adjustment
/vis/set/textLayout    # Revert to normal (left adjusted) layout
/vis/set/textColour    # Revert to default text colour (blue)
#
# Axes, scale, etc.
#/vis/scene/add/scale   # Simple scale line
#/vis/scene/add/axes    # Simple axes: x=red, y=green, z=blue.
/vis/scene/add/eventID # Drawn at end of event
#/vis/scene/add/date    # Date stamp
#/vis/scene/add/logo2D  # Simple logo
#/vis/scene/add/logo    # 3D logo
# Frame
/vis/set/colour red
/vis/set/lineWidth 2
/vis/scene/add/frame   # Simple frame around the view
/vis/set/colour        # Revert to default colour (white)
/vis/set/lineWidth     # Revert to default line width (1.)


##############################
#                            #
#   VISUALIZATION GEOMETRY   #
#                            #
##############################

# To get nice view
/vis/geometry/set/visibility logicWorld 0 false
/vis/viewer/set/style surface

/vis/viewer/set/edge true
/vis/viewer/set/hiddenMarker true
/vis/viewer/set/viewpointThetaPhi -90 0 deg

#############################

#Al Profiles
/vis/geometry/set/colour logicAlProfilePlane1 0 1 0 1 1 #magenta
#/vis/geometry/set/visibility logicAlProfilePlane1 0 0

/vis/geometry/set/colour logicAlProfilePlane2 0 0 0 1 1 #cyan
#/vis/geometry/set/visibility logicAlProfilePlane2 0 0

/vis/geometry/set/colour logicGuideAlProfile_1 0 0.5 0.5 0.5 1 #grey
#/vis/geometry/set/visibility logicGuideAlProfile_1 0 0

/vis/geometry/set/colour logicGuideAlProfile_2 0 0.5 0.5 0.5 1 #grey
#/vis/geometry/set/visibility logicGuideAlProfile_2 0 0

/vis/geometry/set/colour logicGuideAlProfile_3 0 0.5 0.5 0.5 1 #grey
#/vis/geometry/set/visibility logicGuideAlProfile_3 0 0

/vis/geometry/set/colour logicGuideAlProfile_4 0 0.5 0.5 0.5 1 #grey
#/vis/geometry/set/visibility logicGuideAlProfile_4 0 0


#SCINTILLATOR

/vis/geometry/set/colour logicScinP1_1  0 1 1 0 1
#/vis/geometry/set/visibility logicScinP1_1 0 0

/vis/geometry/set/colour logicScinP1_2  0 1 1 0 1
#/vis/geometry/set/visibility logicScinP1_2 0 0

/vis/geometry/set/colour logicScinP1_3  0 1 1 0 1
#/vis/geometry/set/visibility logicScinP1_3 0 0

/vis/geometry/set/colour logicScinP1_4  0 1 1 0 1
#/vis/geometry/set/visibility logicScinP1_4 0 0

/vis/geometry/set/colour logicScinP2_1  0 1 1 0 1
#/vis/geometry/set/visibility logicScinP2_1 0 0

/vis/geometry/set/colour logicScinP2_2  0 1 1 0 1
#/vis/geometry/set/visibility logicScinP2_2 0 0

/vis/geometry/set/colour logicScinP2_3  0 1 1 0 1
#/vis/geometry/set/visibility logicScinP2_3 0 0

/vis/geometry/set/colour logicScinP2_4  0 1 1 0 1
#/vis/geometry/set/visibility logicScinP2_4 0 0
